### ISSUE TITLE
Deserialising metadata fails with ValueError

### ISSUE THREAD

**Issue by rmhsilva** [kylef/refract.py#3]
https://github.com/kylef/refract.py/blob/3a5513d77beda2f2cbb21b8355fe271557ad8255/refract/json.py#L87

Based on the example in https://github.com/refractproject/refract-spec, it looks like "meta" dicts don't need to have an "element" key. However, `deserialise_dict` raises `ValueError` if it doesn't. 

This example (listed in the refract repo above), causes `ValueError`, when run through `JSONDeserialiser.deserialise` (using the `refract.contrib.apielements` registry, although I don't think that matters?).

```json
{
  "element": "object",
  "content": [
    {
      "element": "member",
      "meta": {
        "title": "Name",
        "description": "Name of a person"
      },
      "content": {
        "key": {
          "element": "string",
          "content": "name"
        },
        "value": {
          "element": "string",
          "content": "John Doe"
        }
      }
    },
    {
      "element": "member",
      "meta": {
        "title": "Email",
        "description": "Email address for the person"
      },
      "content": {
        "key": {
          "element": "string",
          "content": "email"
        },
        "value": {
          "element": "string",
          "content": "john@example.com"
        }
      }
    }
  ]
}
```

Full code:

```python
from refract.json import JSONDeserialiser
from refract.contrib.apielements import registry
content = """<JSON above>"""
deserialiser = JSONDeserialiser(registry=registry)
parseResult = deserialiser.deserialise(content)  # raises ValueError

```

**Comment by rmhsilva** [comment]
Actually, digging deeper, it looks like `refract.py` behaves correctly, and the example given above is actually invalid Refract data, according to the spec (https://github.com/refractproject/refract-spec/blob/master/refract-spec.md).

So quite possible this issue can be closed as not actually a bug.

**Comment by kylef** [comment]
@rmhsilva The example you have provided is an older version of Refract (0.6). All our (Apiary) parsers are capable of emitting Refract 1.0 if that is what you are using, check you are using the latest version of parsers.

That said, it is possible to deserialise this older form with this library, there is a "legacy" deserialiser at https://github.com/kylef/refract.py/blob/3a5513d77beda2f2cbb21b8355fe271557ad8255/refract/json.py#L148

**Comment by rmhsilva** [comment]
Thanks for the quick reply @kylef, I agree, my tool (drafter v3.2.7) is emitting old Refract. 

Also thanks for the pointer to the Legacy deserialiser!

Closing, I am more educated now.
